<?php
/**
 * Created by PhpStorm.
 * User: matheus
 * Date: 30/08/19
 * Time: 16:58
 */

namespace MatheusHack\PortoImobiliario\Soap;


/**
 * Class Client
 * @package MatheusHack\PortoImobiliario\Soap
 */
abstract class Client extends \SoapClient
{
    /**
     * Client constructor.
     */
    public function __construct()
    {
        parent::__construct(getenv('IMOBILIARIA_WSDL'), [
            'login' => getenv('IMOBILIARIA_USERNAME'),
            'password' => getenv('IMOBILIARIA_PASSWORD'),
            'exceptions' => 0,
            'trace' => 1,
            'connection_timeout' => 1800,
            'compression' =>  SOAP_COMPRESSION_ACCEPT | SOAP_COMPRESSION_GZIP,
            'encoding' => 'UTF-8',
            'cache_wsdl' => WSDL_CACHE_BOTH,
        ]);
    }

    public function __doRequest($request, $location, $action, $version, $one_way = 0)
    {
        echo "<pre>";var_dump($request);exit;
        parent::__doRequest($request, $location, $action, $version, $one_way); // TODO: Change the autogenerated stub
    }
}