<?php
/**
 * Created by PhpStorm.
 * User: matheus
 * Date: 30/08/19
 * Time: 16:58
 */

namespace MatheusHack\PortoImobiliario\Soap;


/**
 * Class Client
 * @package MatheusHack\PortoImobiliario\Soap
 */
abstract class Client extends \SoapClient
{

    /**
     * Client constructor.
     * @param $wsdl
     */
    public function __construct($wsdl)
    {
        if(file_exists(dirname(__FILE__)."/wsdl/".$wsdl))
            $wsdl = dirname(__FILE__)."/wsdl/".$wsdl;

        parent::__construct($wsdl, [
            'login' => getenv('IMOBILIARIA_USERNAME'),
            'password' => getenv('IMOBILIARIA_PASSWORD'),
            'exceptions' => true,
            'trace' => true,
            'connection_timeout' => 1800,
            'compression' =>  SOAP_COMPRESSION_ACCEPT | SOAP_COMPRESSION_GZIP,
            'encoding' => 'UTF-8',
            'cache_wsdl' => WSDL_CACHE_BOTH,
            'stream_context' => stream_context_create([
                'header' => [
                    'Authorization: Basic c2xoZmluY2E6aG1pamxpMjQ='
                ]
            ])
        ]);
    }

    /**
     * @param string $request
     * @param string $location
     * @param string $action
     * @param int $version
     * @param int $one_way
     * @return string
     */
    public function __doRequest($request, $location, $action, $version, $one_way = 0)
    {
        return parent::__doRequest($request, $location, $action, $version, $one_way); // TODO: Change the autogenerated stub
    }
}